section Section1;

shared sqlComissao = let
    Fonte = "
SELECT
    SE5.E5_FILORIG AS FILIAL,
    MAX(CAST(SE1.E1_EMISSAO AS DATE)) AS DTEMISSAO,
    MAX(SE5.E5_TIPO) AS TIPO,
    SE5.E5_TIPODOC AS TPDOC,
    SUM(SE5.E5_VALOR) AS VALOR,
    SE5.E5_NATUREZ AS NATUREZA,
    MAX(SE5.E5_BANCO) AS BCO,
    MAX(SE5.E5_AGENCIA) AS AG,
    MAX(SE5.E5_CONTA) AS CONTA,
    MAX(SE5.E5_HISTOR) AS OBSERV,
    MAX(SE5.E5_BENEF) AS PAGADOR,
    SE5.E5_NUMERO AS TITULO,
    SE5.E5_PARCELA AS PARC,
    SE5.E5_CLIFOR AS CODCLI,
    SE5.E5_LOJA AS LJCLI,
    SE5.E5_SEQ AS SEQ,
    MAX(SA1.A1_NOME) AS CLIENTE,
    MAX(SA1.A1_MUN) AS MUNICIPIO,
    MAX(SA1.A1_EST) AS UF,
    MAX(CAST(SE5.E5_DATA AS DATE)) AS DTBAIXA,
    MAX(SE5.E5_MOTBX) AS MOTIVOBX,
    MAX(SA1.A1_VEND) AS VENDEDOR,
    MAX(SA3_VEN.A3_FORNECE) AS CODVEND,
    MAX(SA3_VEN.A3_LOJA) AS LJVEND,
    MAX(SA3_VEN.A3_NOME) AS NOME_VENDEDOR,
    CASE
        WHEN MAX(SC5.C5_COMIS1) IS NOT NULL AND MAX(SC5.C5_COMIS1) <> 0 THEN MAX(SC5.C5_COMIS1) / 100
        WHEN MAX(SA1.A1_COMIS) IS NOT NULL AND MAX(SA1.A1_COMIS) <> 0 THEN MAX(SA1.A1_COMIS) / 100
        ELSE MAX(SA3_VEN.A3_COMIS) / 100
    END AS PERCCOMISS_VENDEDOR,
    MAX(SA3_SUP.A3_FORNECE) AS CODGERENTE,
    MAX(SA3_SUP.A3_LOJA) AS LJGERENTE,
    MAX(SA3_SUP.A3_NOME) AS NOME_GERENTE,
    CASE
        WHEN MAX(SA3_SUP.A3_COMIS) = 0 OR MAX(SA3_SUP.A3_COMIS) IS NULL THEN MAX(SA1.A1_COMIS3) / 100
        ELSE MAX(SA3_SUP.A3_COMIS) / 100
    END AS PERCCOMISS_GERENTE,
    MAX(SC5.C5_VEND2) AS PF,
    MAX(SA3_PF1.A3_NOME) AS ""PF DO VENDEDOR"",
    MAX(SC5.C5_COMIS2) / 100 AS PERCCOMISS_PF,
    MAX(SE5.E5_DOCUMEN) AS HISTORICO
FROM SE5010 SE5
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SE5.E5_CLIFOR
    AND SA1.A1_LOJA = SE5.E5_LOJA
LEFT JOIN SE1010 SE1
    ON SE1.D_E_L_E_T_ = ''
    AND SE1.E1_FILIAL = SE5.E5_FILORIG
    AND SE1.E1_NUM = SE5.E5_NUMERO
    AND SE1.E1_PARCELA = SE5.E5_PARCELA
    AND SE1.E1_TIPO = SE5.E5_TIPO
LEFT JOIN SA3010 SA3_VEN
    ON SA3_VEN.D_E_L_E_T_ = ''
    AND SA3_VEN.A3_COD = SA1.A1_VEND
LEFT JOIN SA3010 SA3_SUP
    ON SA3_SUP.D_E_L_E_T_ = ''
    AND SA3_SUP.A3_COD = SA1.A1_VEND3
LEFT JOIN SA3010 SA3_PF
    ON SA3_PF.D_E_L_E_T_ = ''
    AND SA3_PF.A3_COD = SA1.A1_VEND1
LEFT JOIN SC5010 SC5
    ON SC5.D_E_L_E_T_ = ''
    AND SC5.C5_FILIAL = SE5.E5_FILORIG
    AND SC5.C5_NOTA = SE5.E5_NUMERO
LEFT JOIN SA3010 SA3_PF1
    ON SA3_PF1.D_E_L_E_T_ = ''
    AND SA3_PF1.A3_COD = SC5.C5_VEND2
WHERE
    SE5.D_E_L_E_T_ = ''
    AND SE5.E5_MOTBX = 'NOR'
    AND SE5.E5_TABORI = 'FK1'
    AND SE5.E5_TIPO IN ('NF')
    AND SE5.E5_TIPODOC NOT IN ('DC', 'ES', 'JR')
    AND SE5.E5_VALOR <> 0
    AND SE5.E5_DTCANBX = ''
GROUP BY
    SE5.E5_FILORIG,
    SE5.E5_NATUREZ,
    SE5.E5_NUMERO,
    SE5.E5_PARCELA,
    SE5.E5_CLIFOR,
    SE5.E5_LOJA,
    SE5.E5_TIPODOC,
    SE5.E5_SEQ

UNION ALL

SELECT
    SE5.E5_FILORIG AS FILIAL,
    MAX(CAST(SE1.E1_EMISSAO AS DATE)) AS DTEMISSAO,
    MAX(SE5.E5_TIPO) AS TIPO,
    SE5.E5_TIPODOC AS TPDOC,
    SUM(SE5.E5_VALOR) AS VALOR,
    SE5.E5_NATUREZ AS NATUREZA,
    MAX(SE5.E5_BANCO) AS BCO,
    MAX(SE5.E5_AGENCIA) AS AG,
    MAX(SE5.E5_CONTA) AS CONTA,
    MAX(SE5.E5_HISTOR) AS OBSERV,
    MAX(SE5.E5_BENEF) AS PAGADOR,
    SE5.E5_NUMERO AS TITULO,
    SE5.E5_PARCELA AS PARC,
    SE5.E5_CLIFOR AS CODCLI,
    SE5.E5_LOJA AS LJCLI,
    SE5.E5_SEQ AS SEQ,
    MAX(SA1.A1_NOME) AS CLIENTE,
    MAX(SA1.A1_MUN) AS MUNICIPIO,
    MAX(SA1.A1_EST) AS UF,
    MAX(CAST(SE5.E5_DATA AS DATE)) AS DTBAIXA,
    MAX(SE5.E5_MOTBX) AS MOTIVOBX,
    MAX(SA1.A1_VEND) AS VENDEDOR,
    MAX(SA3_VEN.A3_FORNECE) AS CODVEND,
    MAX(SA3_VEN.A3_LOJA) AS LJVEND,
    MAX(SA3_VEN.A3_NOME) AS NOME_VENDEDOR,
    CASE
        WHEN MAX(SC5.C5_COMIS1) IS NOT NULL AND MAX(SC5.C5_COMIS1) <> 0 THEN MAX(SC5.C5_COMIS1) / 100
        WHEN MAX(SA1.A1_COMIS) IS NOT NULL AND MAX(SA1.A1_COMIS) <> 0 THEN MAX(SA1.A1_COMIS) / 100
        ELSE MAX(SA3_VEN.A3_COMIS) / 100
    END AS PERCCOMISS_VENDEDOR,
    MAX(SA3_SUP.A3_FORNECE) AS CODGERENTE,
    MAX(SA3_SUP.A3_LOJA) AS LJGERENTE,
    MAX(SA3_SUP.A3_NOME) AS NOME_GERENTE,
    CASE
        WHEN MAX(SA3_SUP.A3_COMIS) = 0 OR MAX(SA3_SUP.A3_COMIS) IS NULL THEN MAX(SA1.A1_COMIS3) / 100
        ELSE MAX(SA3_SUP.A3_COMIS) / 100
    END AS PERCCOMISS_GERENTE,
    MAX(SC5.C5_VEND2) AS PF,
    MAX(SA3_PF1.A3_NOME) AS ""PF DO VENDEDOR"",
    MAX(SC5.C5_COMIS2) / 100 AS PERCCOMISS_PF,
    MAX(SE5.E5_DOCUMEN) AS HISTORICO
FROM SE5010 SE5
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SE5.E5_CLIFOR
    AND SA1.A1_LOJA = SE5.E5_LOJA
LEFT JOIN SE1010 SE1
    ON SE1.D_E_L_E_T_ = ''
    AND SE1.E1_FILIAL = SE5.E5_FILORIG
    AND SE1.E1_NUM = SE5.E5_NUMERO
    AND SE1.E1_PARCELA = SE5.E5_PARCELA
    AND SE1.E1_TIPO = SE5.E5_TIPO
LEFT JOIN SA3010 SA3_VEN
    ON SA3_VEN.D_E_L_E_T_ = ''
    AND SA3_VEN.A3_COD = SA1.A1_VEND
LEFT JOIN SA3010 SA3_SUP
    ON SA3_SUP.D_E_L_E_T_ = ''
    AND SA3_SUP.A3_COD = SA1.A1_VEND3
LEFT JOIN SA3010 SA3_PF
    ON SA3_PF.D_E_L_E_T_ = ''
    AND SA3_PF.A3_COD = SA1.A1_VEND1
LEFT JOIN SC5010 SC5
    ON SC5.D_E_L_E_T_ = ''
    AND SC5.C5_FILIAL = SE5.E5_FILORIG
    AND SC5.C5_NOTA = SE5.E5_NUMERO
LEFT JOIN SA3010 SA3_PF1
    ON SA3_PF1.D_E_L_E_T_ = ''
    AND SA3_PF1.A3_COD = SC5.C5_VEND2
WHERE
    SE5.D_E_L_E_T_ = ''
    AND SE5.E5_MOTBX = 'CMP'
    AND UPPER(LTRIM(RTRIM(COALESCE(SE5.E5_DOCUMEN, '')))) LIKE '%RA%'
    AND SE5.E5_TABORI = 'FK1'
    AND SE5.E5_TIPO IN ('NF')
    AND SE5.E5_TIPODOC NOT IN ('DC', 'ES', 'JR')
    AND SE5.E5_VALOR <> 0
    AND SE5.E5_DTCANBX = ''
GROUP BY
    SE5.E5_FILORIG,
    SE5.E5_NATUREZ,
    SE5.E5_NUMERO,
    SE5.E5_PARCELA,
    SE5.E5_CLIFOR,
    SE5.E5_LOJA,
    SE5.E5_TIPODOC,
    SE5.E5_SEQ
    "
in
    Fonte;

shared dComissao = let
    Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlComissao, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"DTEMISSAO", type date}, {"DTBAIXA", type date}}),
  #"Valor substituído" = Table.ReplaceValue(#"Tipo de coluna alterado", null, 0, Replacer.ReplaceValue, {"PERCCOMISS_PF"}),
  #"Personalização adicionada" = Table.AddColumn(#"Valor substituído", "VR COMISSAO_VEND", each [VALOR] * [PERCCOMISS_VENDEDOR]),
  #"Personalização adicionada 1" = Table.AddColumn(#"Personalização adicionada", "VR COMISSAO_GERENTE", each [VALOR] * [PERCCOMISS_GERENTE]),
  #"Personalização adicionada 2" = Table.AddColumn(#"Personalização adicionada 1", "VR PF", each [VALOR] * [PERCCOMISS_PF]),
  #"Colunas reordenadas" = Table.ReorderColumns(#"Personalização adicionada 2", {"FILIAL", "DTEMISSAO", "TIPO", "TPDOC", "VALOR", "NATUREZA", "BCO", "AG", "CONTA", "OBSERV", "PAGADOR", "TITULO", "PARC", "CODCLI", "LJCLI", "CLIENTE", "MUNICIPIO", "UF", "DTBAIXA", "MOTIVOBX", "VENDEDOR", "CODVEND", "LJVEND", "NOME_VENDEDOR", "PERCCOMISS_VENDEDOR", "VR COMISSAO_VEND", "CODGERENTE", "LJGERENTE", "NOME_GERENTE", "PERCCOMISS_GERENTE", "VR COMISSAO_GERENTE", "PF", "PF DO VENDEDOR", "PERCCOMISS_PF", "VR PF"})
in
    #"Colunas reordenadas";

shared dVendedores = let
    Fonte = Excel.CurrentWorkbook(){[Name="dVendedores"]}[Content],
    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([cnpj1] <> "NÃO EMITE NF" and [cnpj1] <> "NÃO VENDE MAIS")),
    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Linhas Filtradas", {"_CODVEND"}, "Atributo", "cnpj"),
    #"Retirar ." = Table.ReplaceValue(#"Colunas Não Dinâmicas",".","",Replacer.ReplaceText,{"cnpj"}),
    #"Retirar /" = Table.ReplaceValue(#"Retirar .","/","",Replacer.ReplaceText,{"cnpj"}),
    #"Retirar -" = Table.ReplaceValue(#"Retirar /","-","",Replacer.ReplaceText,{"cnpj"})
in
    #"Retirar -";

shared __STATUS__ = let
    Fonte = if Table.RowCount(Table.Combine({dComissao})) > 0 then DateTime.LocalNow() else "Pendente"
in
    Fonte;