section Section1;

shared dDestino = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\PUBLICA\T.I\01. BASES\fManual.xlsx"), null, true),
    dDestino_Table = Fonte{[Item="dDestino",Kind="Table"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(dDestino_Table,{{"Coluna 1", type text}, {"Coluna 2", type text}})
in
    #"Tipo Alterado";

shared dMotivoDev = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\PUBLICA\T.I\01. BASES\fManual.xlsx"), null, true),
    dMotivoDev_Table = Fonte{[Item="dMotivoDev",Kind="Table"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(dMotivoDev_Table,{{"SIGLA", type text}, {"MOTIVO", type text}, {"Coluna 1", type text}})
in
    #"Tipo Alterado";

shared fFaturamentoDataVale = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\PUBLICA\T.I\01. BASES\fManual.xlsx"), null, true),
    fFaturamentoDataVale_Table = Fonte{[Item="fFaturamentoDataVale",Kind="Table"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(fFaturamentoDataVale_Table,{{"Coluna 1", Int64.Type}, {"Coluna 2", Int64.Type}, {"Coluna 3", type text}, {"Coluna 4", type text}, {"Coluna 5", type text}, {"Coluna 6", type text}, {"Coluna 7", type text}, {"Coluna 8", Int64.Type}, {"Coluna 9", type text}, {"Coluna 10", type date}, {"Coluna 11", type text}, {"Coluna 12", Int64.Type}})
in
    #"Tipo Alterado";

shared sqlAcordoComercial = let
    Fonte = "
    SELECT 
SD1.D1_FILIAL AS FILIAL,
SD1.D1_ITEM AS ITEM,
     CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD1.D1_COD = 'PA01020010-CX' THEN 'PA01020010'
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN 'PA01010006'
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN 'PA01010011'
        WHEN SD1.D1_COD = 'PA01020034-CX' THEN 'PA01020034'
        ELSE SD1.D1_COD 
    END AS CODPROD,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD1.D1_COD = 'PA01020010-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN 'KG'
        WHEN SD1.D1_COD = 'PA01020034-CX' THEN 'KG'
        ELSE SD1.D1_UM 
    END AS UM,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN SD1.D1_QUANT * 10 
		WHEN SD1.D1_COD = 'PA01020010-CX' THEN SD1.D1_QUANT * 2.016
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN SD1.D1_QUANT * 4
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN SD1.D1_QUANT * 2.016
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN SD1.D1_QUANT * 10
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN SD1.D1_QUANT * 9.6
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN SD1.D1_QUANT * 10
        WHEN SD1.D1_COD = 'PA01020034-CX' THEN SD1.D1_QUANT * 13.44
        ELSE SD1.D1_QUANT 
    END AS QTD,
SD1.D1_VUNIT AS VRUNIT,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN SD1.D1_VUNIT / 10 
		WHEN SD1.D1_COD = 'PA01020010-CX' THEN SD1.D1_VUNIT / 2.016
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN SD1.D1_VUNIT / 4
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN SD1.D1_VUNIT / 2.016
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN SD1.D1_VUNIT / 10
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN SD1.D1_VUNIT / 9.6
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN SD1.D1_VUNIT / 10
        WHEN SD1.D1_COD = 'PA01020034-CX' THEN SD1.D1_VUNIT / 13.44
        ELSE SD1.D1_VUNIT
    END AS PRCUNIT,
SD1.D1_TOTAL AS VRTOTAL,
SD1.D1_NFORI AS NFORIGEM,
SD1.D1_FORNECE AS CLIENTE,
SD1.D1_LOJA AS LJCLI,
SD1.D1_SERIE AS TIPO,
CONVERT(VARCHAR, CONVERT(DATE, SD1.D1_EMISSAO, 103), 105) AS EMISSAO,
SD1.D1_ITEMORI AS ITEMORI
FROM SD1010 SD1 
WHERE SD1.D_E_L_E_T_ = '' AND SD1.D1_TES IN ('050', '052')
    "
in
    Fonte;

shared fAcordoComercial = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlAcordoComercial, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"EMISSAO", type date}})
in
  #"Tipo de coluna alterado";

shared sqlCoopevalRemess = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
    SD2.D2_ITEM AS ITEM,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'PA01010006'
        ELSE SD2.D2_COD 
    END AS CODPROD,
	SB1.B1_DESC AS PRODUTO,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_QUANT * 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_QUANT * 9.6
        ELSE SD2.D2_QUANT 
    END AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_PRCVEN / 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_PRCVEN / 2.016
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_PRCVEN / 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_PRCVEN / 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_PRCVEN / 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_PRCVEN / 9.6
        ELSE SD2.D2_PRCVEN 
    END AS PRCUNIT,
    SD2.D2_TOTAL AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_CLIENTE AS CODCLI,
    SD2.D2_LOJA AS LJCLI,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CONVERT(VARCHAR, CONVERT(DATE, SD2.D2_EMISSAO, 103), 105) AS _DTEMISSAO,
CASE 
    WHEN SA1.A1_COND = '' THEN SF2.F2_COND
    ELSE SA1.A1_COND
END AS _CONDPGTO,
	SC5.C5_TABELA AS TABPRECO,
    SF2.F2_DUPL AS _DUPLICATA,
    SF2.F2_EST AS _ESTADO,
    SF2.F2_TIPOCLI AS _TIPOCLI,
    SA1.A1_VEND AS _CODVEND,
	SA1.A1_VEND1 AS _CONDESPECIAL,
	SF2.F2_TIPO AS TIPO,
    SC5.C5_X_REFAT AS NFORIREFATURA
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ = ''
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SD2.D2_CLIENTE
    AND SA1.A1_LOJA = SD2.D2_LOJA
INNER JOIN SB1010 SB1
	ON SB1.D_E_L_E_T_ = ''
	AND SB1.B1_COD = SD2.D2_COD	
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250430'
	AND SD2.D2_CLIENTE = '07390806'
    "
in
    Fonte;

shared fCoopevalRemess = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlCoopevalRemess, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"_DTEMISSAO", type date}}),
  #"Nome do mês inserido" = Table.AddColumn(#"Tipo de coluna alterado", "Nome do mês", each Date.MonthName([_DTEMISSAO]), type nullable text),
  #"Tipo de coluna alterado 1" = Table.TransformColumnTypes(#"Nome do mês inserido", {{"FILIAL", Int64.Type}})
in
  #"Tipo de coluna alterado 1";

shared sqlDevoluções = let
    Fonte = "
SELECT 
    SD1.D1_FILIAL AS FILIAL,
    SD1.D1_ITEM AS ITEM,
    SD1.D1_DOC AS NF,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN 'PA01010001' 
        WHEN SD1.D1_COD = 'PA01020010-CX' THEN 'PA01020010'
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN 'PA01010006'
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN 'PA01010011'
        ELSE SD1.D1_COD 
    END AS CODPROD,
    CASE 
        WHEN SD1.D1_COD IN ('PA01010001-CX', 'PA01020010-CX', 'PA01020012-CX', 'PA01020021-CX', 'PA01010005-CX', 'PA01010006-CX', 'PA01010011-CX') THEN 'KG'
        ELSE SD1.D1_UM 
    END AS UM,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN SD1.D1_QUANT * 10 
        WHEN SD1.D1_COD = 'PA01020010-CX' THEN SD1.D1_QUANT * 2.016
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN SD1.D1_QUANT * 4
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN SD1.D1_QUANT * 2.016
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN SD1.D1_QUANT * 10
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN SD1.D1_QUANT * 9.6
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN SD1.D1_QUANT * 10
        ELSE SD1.D1_QUANT 
    END AS QTD,
    CASE 
        WHEN SD1.D1_COD = 'PA01010001-CX' THEN SD1.D1_VUNIT / 10 
        WHEN SD1.D1_COD = 'PA01020010-CX' THEN SD1.D1_VUNIT / 2.016
        WHEN SD1.D1_COD = 'PA01020012-CX' THEN SD1.D1_VUNIT / 4
        WHEN SD1.D1_COD = 'PA01020021-CX' THEN SD1.D1_VUNIT / 2.016
        WHEN SD1.D1_COD = 'PA01010005-CX' THEN SD1.D1_VUNIT / 10
        WHEN SD1.D1_COD = 'PA01010006-CX' THEN SD1.D1_VUNIT / 9.6
        WHEN SD1.D1_COD = 'PA01010011-CX' THEN SD1.D1_VUNIT / 10
        ELSE SD1.D1_VUNIT 
    END AS VRUNIT,
    SD1.D1_TOTAL - SD1.D1_VALDESC AS VRTOTAL,
    CONVERT(VARCHAR, CONVERT(DATE, SF2.F2_EMISSAO, 103), 105) AS DTAEMISSNFORI,
    SD1.D1_ITEMORI AS ITEMORI,
    SD1.D1_NFORI AS NFORIGEM,
    SD1.D1_FORNECE AS CLIENTE,
    SD1.D1_LOJA AS LJCLI,
    SD1.D1_SERIE AS SERIE,
    SD1.D1_COR AS MOTIVODEV,
    SD1.D1_CHASSI AS DESTINO,
    SF1.F1_FORMUL,
    CONVERT(VARCHAR, CONVERT(DATE, SD1.D1_EMISSAO, 103), 105) AS EMISSAO,
    CONVERT(VARCHAR, CONVERT(DATE, SD1.D1_DTDIGIT, 103), 105) AS LANCAMENTO
FROM SD1010 SD1 
INNER JOIN SF1010 SF1 ON SF1.D_E_L_E_T_ = ''
    AND SF1.F1_FILIAL = SD1.D1_FILIAL
    AND SF1.F1_DOC = SD1.D1_DOC
    AND SF1.F1_SERIE = SD1.D1_SERIE
    AND SF1.F1_FORNECE = SD1.D1_FORNECE
    AND SF1.F1_LOJA = SD1.D1_LOJA
LEFT JOIN SF2010 SF2 ON SF2.D_E_L_E_T_ = ''
    AND SF2.F2_FILIAL = SD1.D1_FILIAL
    AND SF2.F2_DOC = SD1.D1_NFORI
WHERE SD1.D_E_L_E_T_ = '' 
  AND (
        SD1.D1_CF IN ('1202','1203','1410','1411','1201','1903','2410','2411','2201','2202','2203','2911','2551')
     OR
        (SD1.D1_TIPO = 'D' AND SD1.D1_CF = '')
      )
  AND SD1.D1_COD LIKE '%PA%'
  AND (SD1.D1_FORNECE <> '97316293' AND SD1.D1_FORNECE <> '30704321')
  AND SD1.D1_SERIE NOT LIKE '%AC%'
  AND SF1.F1_STATUS <> ''
  AND (
        SD1.D1_FILIAL <> '01004' 
        OR SD1.D1_DOC NOT IN (
            '000016378','000016379', '000016380', 
            '000016621', '000016622', '000016623', 
            '000016625', '000016626', '000016696', 
            '000016714', '000016715', '000016915', 
            '000016916', '000016917'
        )
      )
    AND (
        SD1.D1_FILIAL <> '01006' 
        OR SD1.D1_DOC NOT IN  (
            '000045676', '000045699'
        )
    )
    "
in
    Fonte;

shared fDevoluções = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlDevoluções, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"EMISSAO", type date}, {"LANCAMENTO", type date}, {"DTAEMISSNFORI", type date}}),
  #"Valor substituído" = Table.ReplaceValue(#"Tipo de coluna alterado", " ", "N", Replacer.ReplaceValue, {"F1_FORMUL"})
in
    #"Valor substituído";

shared sqlfFaturamento = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
    SD2.D2_ITEM AS ITEM,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'PA01010011'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'PA01010006'
        WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'PA01010011'
        WHEN SD2.D2_COD = 'PA01020002-CX' THEN 'PA01020002'
        ELSE SD2.D2_COD 
    END AS CODPROD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_QUANT * 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_QUANT * 9.6
        WHEN SD2.D2_COD = 'PA01010011-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01020002-CX' THEN SD2.D2_QUANT * 4
        ELSE SD2.D2_QUANT 
    END AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020002-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR) / (SD2.D2_QUANT * 10) 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 2.016)
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 10)
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 4)
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 2.016)
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 10)
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 9.6)
        WHEN SD2.D2_COD = 'PA01010011-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 10)
        WHEN SD2.D2_COD = 'PA01020002-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 4)
        ELSE (SD2.D2_TOTAL + SD2.D2_DESCZFR) / SD2.D2_QUANT
    END AS PRCUNIT,
    SD2.D2_TOTAL AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_CLIENTE AS CODCLI,
    SD2.D2_LOJA AS LJCLI,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CAST(SD2.D2_EMISSAO AS DATE) AS _DTEMISSAO,
CASE 
    WHEN SA1.A1_COND = '' THEN SF2.F2_COND
    ELSE SA1.A1_COND
END AS _CONDPGTO,
	SC5.C5_TABELA AS TABPRECO,
    SF2.F2_DUPL AS _DUPLICATA,
    SF2.F2_EST AS _ESTADO,
    SF2.F2_TIPOCLI AS _TIPOCLI,
    SA1.A1_VEND AS _CODVEND,
	SA1.A1_VEND1 AS _CONDESPECIAL,
	SF2.F2_TIPO AS TIPO,
    SC5.C5_X_REFAT AS NFORIREFATURA,
    SC5.C5_X_TPENT AS 'TIPO DE ENTREGA',
    SD2.D2_PICM AS ICMS,
    SD2.D2_ALQPIS AS PIS,
    SD2.D2_ALQCOF AS COFINS,
    SD2.D2_ICMSRET AS ICMSST
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ = ''
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SD2.D2_CLIENTE
    AND SA1.A1_LOJA = SD2.D2_LOJA
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250131'
	AND (SD2.D2_CLIENTE <> '97316293')
	AND SF2.F2_TIPO <> 'B'
	AND (SD2.D2_FILIAL <> '01004' OR SD2.D2_DOC NOT IN ('000029000', '000012896', '000012898', '000012899', '000012900', '000012901', '000012908', '000012909', '000012910', '000012911', '000012912', '000015334', '000015335', '000015336', '000015455', '000015456', '000015457', '000016294', '000016295', '000016296', '000016298', '000016299', '000016300', '000016320', '000016321', '000016322', '000016323', '000016324', '000018493', '000023971', '000025043', '000030015', '000030016', '000030017', '000030018', '000030019'))
	AND (SD2.D2_FILIAL <> '03001' OR SD2.D2_DOC NOT IN  ('000002073', '000002082'))
    AND SD2.D2_CF IN ('6101', '5102', '6118', '5101', '5403', '6110', '6401', '6107', '6102', '5401', '6403', '6108', '6109', '5109', '6501') 
	AND SD2.D2_FILIAL IN ('01001', '01003', '01004', '01005', '01006', '01007', '01009', '01010', '01011')
    "
in
    Fonte;

shared fFaturamento = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlfFaturamento, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"_DTEMISSAO", type date}}),
  #"Colunas mescladas" = Table.CombineColumns(#"Tipo de coluna alterado", {"CODCLI", "LJCLI"}, Combiner.CombineTextByDelimiter("", QuoteStyle.None), "_CHAVECLIENTE"),
  #"Colunas reordenadas" = Table.ReorderColumns(#"Colunas mescladas", {"FILIAL", "NFE", "_SERIE", "CODPROD", "ITEM", "QTD", "UM", "PRCUNIT", "TOTAL", "CFOP", "_CHAVECLIENTE", "_DTEMISSAO", "_CONDPGTO", "_DUPLICATA", "_ESTADO", "_TIPOCLI", "_CODVEND", "TIPO"})
in
    #"Colunas reordenadas";

shared sqlRefaturamento = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'PA01010006'
        ELSE SD2.D2_COD 
    END AS CODPROD,
    SUM(CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_QUANT * 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_QUANT * 9.6
        ELSE SD2.D2_QUANT 
    END) AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_PRCVEN / 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_PRCVEN / 2.016
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_PRCVEN / 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_PRCVEN / 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_PRCVEN / 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_PRCVEN / 9.6
        ELSE SD2.D2_PRCVEN 
    END AS PRCUNIT,
    SUM(SD2.D2_TOTAL) AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CONVERT(VARCHAR, CONVERT(DATE, SD2.D2_EMISSAO, 103), 105) AS _DTEMISSAO,    
    RIGHT(REPLICATE('0', 9) + ISNULL(LTRIM(RTRIM(SC5.C5_X_REFAT)), ''), 9) AS NFORIREFATURA
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ = ''
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SD2.D2_CLIENTE
    AND SA1.A1_LOJA = SD2.D2_LOJA
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250131'
	AND SD2.D2_FILIAL IN ('01001', '01003', '01004', '01005', '01006', '01007', '01009', '01010', '01011')
    AND SC5.C5_X_REFAT <> ''
GROUP BY
    SD2.D2_FILIAL,
    SD2.D2_COD,
    SD2.D2_UM,
    SD2.D2_CF,
    SD2.D2_PRCVEN,
    SD2.D2_DOC,
    SD2.D2_SERIE,
    SD2.D2_EMISSAO,
    SC5.C5_X_REFAT
    "
in
    Fonte;

shared fRefaturamento = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlRefaturamento, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"_DTEMISSAO", type date}})
in
  #"Tipo de coluna alterado";

shared sqlRemIndustrializacao = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
    SD2.D2_ITEM AS ITEM,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
        ELSE SD2.D2_COD 
    END AS CODPROD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
        ELSE SD2.D2_QUANT 
    END AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_PRCVEN / 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_PRCVEN / 2.016
        ELSE SD2.D2_PRCVEN 
    END AS PRCUNIT,
    SD2.D2_TOTAL AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_CLIENTE AS CODCLI,
    SD2.D2_LOJA AS LJCLI,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CONVERT(VARCHAR, CONVERT(DATE, SD2.D2_EMISSAO, 103), 105) AS _DTEMISSAO,
    SF2.F2_COND AS _CONDPGTO,
	SC5.C5_TABELA AS TABPRECO,
    SF2.F2_DUPL AS _DUPLICATA,
    SF2.F2_EST AS _ESTADO,
    SF2.F2_TIPOCLI AS _TIPOCLI,
    SF2.F2_VEND1 AS _CODVEND,
	SF2.F2_VEND2 AS _CONDESPECIAL,
	SF2.F2_TIPO AS TIPO
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ <> '*'
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250131'
	AND SD2.D2_CLIENTE <> '97316293'
    AND SD2.D2_CF IN ('5901', '5903', '6901', '6903') 
	AND SD2.D2_FILIAL IN ('01001', '01003', '01004', '01005', '01006', '01007', '01009', '01010', '01011')
    "
in
    Fonte;

shared fRemIndustrializacao = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlRemIndustrializacao, CommandTimeout=#duration(69, 10, 39, 0)])
in
    Fonte;

shared sqlRemTriangular = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
    SD2.D2_ITEM AS ITEM,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
        ELSE SD2.D2_COD 
    END AS CODPROD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
        ELSE SD2.D2_QUANT 
    END AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_PRCVEN / 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_PRCVEN / 2.016
        ELSE SD2.D2_PRCVEN 
    END AS PRCUNIT,
    SD2.D2_TOTAL AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_CLIENTE AS CODCLI,
    SD2.D2_LOJA AS LJCLI,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CONVERT(VARCHAR, CONVERT(DATE, SD2.D2_EMISSAO, 103), 105) AS _DTEMISSAO,
    SF2.F2_COND AS _CONDPGTO,
	SC5.C5_TABELA AS TABPRECO,
    SF2.F2_DUPL AS _DUPLICATA,
    SF2.F2_EST AS _ESTADO,
    SF2.F2_TIPOCLI AS _TIPOCLI,
    SF2.F2_VEND1 AS _CODVEND,
	SF2.F2_VEND2 AS _CONDESPECIAL,
	SF2.F2_TIPO AS TIPO
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ <> '*'
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250131'
	AND SD2.D2_CLIENTE <> '97316293'
    AND SD2.D2_CF IN ('5901', '5903', '6901', '6903') 
	AND SD2.D2_FILIAL IN ('01001', '01003', '01004', '01005', '01006', '01007', '01009', '01010', '01011')
    "
in
    Fonte;

shared fRemTriangular = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlRemTriangular, CommandTimeout=#duration(69, 10, 39, 0)]),
  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Fonte, {{"_DTEMISSAO", type date}})
in
  #"Tipo de coluna alterado";

shared __STATUS__ = let
    Fonte = if Table.RowCount(Table.Combine({fRemTriangular, dDestino, dMotivoDev, fFaturamentoDataVale, fAcordoComercial, fCoopevalRemess, fDevoluções, fFaturamento, fRefaturamento, fRemIndustrializacao})) > 0 then DateTime.LocalNow() else "Pendente"
in
    Fonte;

shared __SQL__ = let
    Fonte = #shared,
    #"Convertido em Tabela" = Record.ToTable(Fonte),
    #"Linhas Filtradas" = Table.SelectRows(#"Convertido em Tabela", each Text.StartsWith([Name], "sql"))
in
    #"Linhas Filtradas";

shared sqlfFaturamentoBonif = let
    Fonte = "
SELECT 
    SD2.D2_FILIAL AS FILIAL,
    SD2.D2_ITEM AS ITEM,
     CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'PA01010001' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'PA01020010'
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'PA01010011'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'PA01020012'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'PA01020021'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'PA01010005'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'PA01010006'
        ELSE SD2.D2_COD 
    END AS CODPROD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN SD2.D2_QUANT * 10 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN SD2.D2_QUANT * 2.016
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN SD2.D2_QUANT * 4
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN SD2.D2_QUANT * 2.016
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN SD2.D2_QUANT * 10
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN SD2.D2_QUANT * 9.6
        ELSE SD2.D2_QUANT 
    END AS QTD,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN 'KG' 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN 'KG'
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN 'KG'
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN 'KG'
        ELSE SD2.D2_UM 
    END AS UM,
    CASE 
        WHEN SD2.D2_COD = 'PA01010001-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR) / (SD2.D2_QUANT * 10) 
		WHEN SD2.D2_COD = 'PA01020010-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 2.016)
		WHEN SD2.D2_COD = 'PA01010011-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 10)
        WHEN SD2.D2_COD = 'PA01020012-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 4)
        WHEN SD2.D2_COD = 'PA01020021-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 2.016)
        WHEN SD2.D2_COD = 'PA01010005-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 10)
        WHEN SD2.D2_COD = 'PA01010006-CX' THEN (SD2.D2_TOTAL + SD2.D2_DESCZFR)/ (SD2.D2_QUANT * 9.6)
        ELSE (SD2.D2_TOTAL + SD2.D2_DESCZFR) / SD2.D2_QUANT
    END AS PRCUNIT,
    SD2.D2_TOTAL AS TOTAL,
    SD2.D2_CF AS CFOP,
    SD2.D2_CLIENTE AS CODCLI,
    SD2.D2_LOJA AS LJCLI,
    SD2.D2_DOC AS NFE,
	SD2.D2_SERIE AS _SERIE,
    CAST(SD2.D2_EMISSAO AS DATE) AS _DTEMISSAO,
CASE 
    WHEN SA1.A1_COND = '' THEN SF2.F2_COND
    ELSE SA1.A1_COND
END AS _CONDPGTO,
	SC5.C5_TABELA AS TABPRECO,
    SF2.F2_DUPL AS _DUPLICATA,
    SF2.F2_EST AS _ESTADO,
    SF2.F2_TIPOCLI AS _TIPOCLI,
    SA1.A1_VEND AS _CODVEND,
	SA1.A1_VEND1 AS _CONDESPECIAL,
	SF2.F2_TIPO AS TIPO,
    SC5.C5_X_REFAT AS NFORIREFATURA,
    SC5.C5_X_TPENT AS 'TIPO DE ENTREGA',
    SD2.D2_PICM AS ICMS,
    SD2.D2_ALQPIS AS PIS,
    SD2.D2_ALQCOF AS COFINS,
    SD2.D2_ICMSRET AS ICMSST
FROM SD2010 SD2
LEFT JOIN SF2010 SF2 
    ON SF2.D_E_L_E_T_ = ''
	AND SD2.D2_FILIAL = SF2.F2_FILIAL
    AND SD2.D2_DOC = SF2.F2_DOC
    AND SD2.D2_CLIENTE = SF2.F2_CLIENTE
    AND SD2.D2_LOJA = SF2.F2_LOJA
INNER JOIN SC5010 SC5
	ON SC5.D_E_L_E_T_ = ''
	AND SC5.C5_FILIAL = SD2.D2_FILIAL
	AND SC5.C5_NUM = SD2.D2_PEDIDO
INNER JOIN SA1010 SA1
    ON SA1.D_E_L_E_T_ = ''
    AND SA1.A1_COD = SD2.D2_CLIENTE
    AND SA1.A1_LOJA = SD2.D2_LOJA
WHERE 
    SD2.D_E_L_E_T_ <> '*' 
    AND (SF2.D_E_L_E_T_ <> '*' OR SF2.D_E_L_E_T_ IS NULL) 
	AND SD2.D2_EMISSAO > '20250131'
	AND (SD2.D2_CLIENTE <> '97316293')
	AND SF2.F2_TIPO <> 'B'
    AND SD2.D2_CF IN ('6910', '5910', '5911', '6911') 
	AND SD2.D2_FILIAL IN ('01001', '01003', '01004', '01005', '01006', '01007', '01009', '01010', '01011')
    "
in
    Fonte;

shared fFaturamentoBonif = let
  Fonte = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [Query=sqlfFaturamentoBonif, CommandTimeout=#duration(69, 10, 39, 0)]),
    #"Texto Aparado" = Table.TransformColumns(Fonte,{{"CODPROD", Text.Trim, type text}})
in
    #"Texto Aparado";