section Section1;

shared PEDIDOSEMBARQUE = let
  Origem = Sql.Database("201.157.243.99,1725", "CJ9SWK_168962_PR_PD", [CommandTimeout=#duration(6, 22, 40, 0), Query="SELECT#(lf)    SC9.C9_FILIAL AS FILIAL,#(lf)    SC9.C9_PEDIDO AS PEDIDO,#(lf)    MAX(SC6.C6_NUMPCOM) AS PEDIDOCLIENTE,#(lf)    MAX(#(lf)        CASE #(lf)            WHEN SC5.C5_X_TPENT = '1' THEN 'FOB' #(lf)            WHEN SC5.C5_X_TPENT = '2' THEN 'CARRO FECHADO' #(lf)            WHEN SC5.C5_X_TPENT = '3' THEN 'CARRO FECHADO ATE 06' #(lf)            WHEN SC5.C5_X_TPENT = '4' THEN 'CROSS' #(lf)            WHEN SC5.C5_X_TPENT = '5' THEN 'CROSS -1TON' #(lf)            ELSE SC5.C5_X_TPENT#(lf)        END#(lf)    ) AS 'TIPO DE ENTREGA',#(lf)    SC9.C9_CLIENTE AS CODCLI,#(lf)    SC9.C9_LOJA AS LJCLI,#(lf)    MAX(CONVERT(VARCHAR, C5_EMISSAO, 105)) AS EMISSAOPED,#(lf)    MAX(SC5.C5_TIPO) AS TIPOMOV,#(lf)    MAX(COALESCE(SA1.A1_NOME, SA2.A2_NOME)) AS CLIENTE,#(lf)    MAX(COALESCE(SA1.A1_MUN, SA2.A2_MUN)) AS MUNICIPIO,#(lf)    MAX(COALESCE(SA1.A1_EST, SA2.A2_EST)) AS ESTADO,#(lf)    MAX(COALESCE(SA1.A1_END, SA2.A2_END)) AS ENDEREÇO,#(lf)    MAX(COALESCE(SA1.A1_BAIRRO, SA2.A2_BAIRRO)) AS BAIRRO,#(lf)    CASE #(lf)        WHEN SC9.C9_PRODUTO = 'PA01010001-CX' THEN 'PA01010001' #(lf)        WHEN SC9.C9_PRODUTO = 'PA01020010-CX' THEN 'PA01020010'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01010011-CX' THEN 'PA01010011'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01020012-CX' THEN 'PA01020012'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01020021-CX' THEN 'PA01020021'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01010005-CX' THEN 'PA01010005'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01010006-CX' THEN 'PA01010006'#(lf)        WHEN SC9.C9_PRODUTO = 'PA01020002-CX' THEN 'PA01020002'#(lf)        ELSE SC9.C9_PRODUTO#(lf)    END AS CODPROD,#(lf)    MAX(SB1.B1_DESC) AS PRODUTO,#(lf)    MAX(#(lf)        CASE #(lf)            WHEN SC9.C9_PRODUTO = 'PA01010001-CX' THEN SC9.C9_QTDLIB * 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020010-CX' THEN SC9.C9_QTDLIB * 2.016#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010011-CX' THEN SC9.C9_QTDLIB * 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020012-CX' THEN SC9.C9_QTDLIB * 4#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020021-CX' THEN SC9.C9_QTDLIB * 2.016#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010005-CX' THEN SC9.C9_QTDLIB * 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010006-CX' THEN SC9.C9_QTDLIB * 9.6#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020002-CX' THEN SC9.C9_QTDLIB * 4#(lf)            ELSE SC9.C9_QTDLIB #(lf)        END#(lf)    ) AS QTD,#(lf)    MAX(#(lf)        CASE #(lf)            WHEN SC9.C9_PRODUTO = 'PA01010001-CX' THEN SC9.C9_PRCVEN / 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020010-CX' THEN SC9.C9_PRCVEN / 2.016#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010011-CX' THEN SC9.C9_PRCVEN / 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020012-CX' THEN SC9.C9_PRCVEN / 4#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020021-CX' THEN SC9.C9_PRCVEN / 2.016#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010005-CX' THEN SC9.C9_PRCVEN / 10#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010006-CX' THEN SC9.C9_PRCVEN / 9.6#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010002-CX' THEN SC9.C9_PRCVEN / 4#(lf)            ELSE SC9.C9_PRCVEN #(lf)        END#(lf)    ) AS PRCUNIT,#(lf)    MAX(#(lf)        CASE #(lf)            WHEN SC9.C9_PRODUTO = 'PA01010001-CX' THEN (SC9.C9_QTDLIB * 10) * (SC9.C9_PRCVEN / 10)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020010-CX' THEN (SC9.C9_QTDLIB * 2.016) * (SC9.C9_PRCVEN / 2.016)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010011-CX' THEN (SC9.C9_QTDLIB * 10) * (SC9.C9_PRCVEN / 10)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020012-CX' THEN (SC9.C9_QTDLIB * 4) * (SC9.C9_PRCVEN / 4)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020021-CX' THEN (SC9.C9_QTDLIB * 2.016) * (SC9.C9_PRCVEN / 2.016)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010005-CX' THEN (SC9.C9_QTDLIB * 10) * (SC9.C9_PRCVEN / 10)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010006-CX' THEN (SC9.C9_QTDLIB * 9.6) * (SC9.C9_PRCVEN / 9.6)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010002-CX' THEN (SC9.C9_QTDLIB * 4) * (SC9.C9_PRCVEN / 4)#(lf)            ELSE SC9.C9_QTDLIB * SC9.C9_PRCVEN #(lf)        END#(lf)    ) AS TOTAL,#(lf)    MAX(#(lf)        CASE #(lf)            WHEN SC9.C9_PRODUTO = 'PA01010001-CX' THEN (SC9.C9_QTDLIB * 10) * (SB1.B1_PESBRU / 10) #(lf)            WHEN SC9.C9_PRODUTO = 'PA01020010-CX' THEN (SC9.C9_QTDLIB * 2.016) * (SB1.B1_PESBRU / 2.016)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010011-CX' THEN (SC9.C9_QTDLIB * 10) * (SB1.B1_PESBRU / 10)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020012-CX' THEN (SC9.C9_QTDLIB * 4) * (SB1.B1_PESBRU / 4)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01020021-CX' THEN (SC9.C9_QTDLIB * 2.016) * (SB1.B1_PESBRU / 2.016)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010005-CX' THEN (SC9.C9_QTDLIB * 10) * (SB1.B1_PESBRU / 10)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010006-CX' THEN (SC9.C9_QTDLIB * 9.6) * (SB1.B1_PESBRU / 9.6)#(lf)            WHEN SC9.C9_PRODUTO = 'PA01010002-CX' THEN (SC9.C9_QTDLIB * 4) * (SB1.B1_PESBRU / 4)#(lf)            ELSE SC9.C9_QTDLIB * SB1.B1_PESBRU#(lf)        END#(lf)    ) AS ""PESO BRUTO"",#(lf)    MAX(SC6.C6_LOCAL) AS ARMAZEM,#(lf)    MAX(SC6.C6_TES) AS TES,#(lf)    MAX(SF4.F4_TEXTO) AS TIPOSAIDA,#(lf)    MAX(SC5.C5_CONDPAG) AS CODCP,#(lf)    MAX(SE4.E4_COND) AS CONDPAG,#(lf)    MAX(SE4.E4_DESCRI) AS CONDICAO,#(lf)    MAX(SA1.A1_X_FREC) AS TIPORECEB,#(lf)    MAX(SC5.C5_VEND1) AS CODVEND,#(lf)    MAX(SA3.A3_NOME) AS VENDEDOR,#(lf)    MAX(SC5.C5_VEND3) AS CODGER,#(lf)    MAX(SA33.A3_NOME) AS GERENTE,#(lf)    SC9.C9_ITEM AS ITEM,#(lf)    SC9.C9_SEQUEN AS SEQ,#(lf)    MAX(CONVERT(VARCHAR, SF2.F2_EMISSAO, 105)) AS EMISSAONF,#(lf)    MAX(SC9.C9_NFISCAL) AS NF,#(lf)    MAX(SC9.C9_SERIENF) AS SERIE,#(lf)    MAX(SC9.C9_CARGA) AS CARGA,#(lf)    MAX(CONVERT(VARCHAR, DAK.DAK_DATA, 105)) AS DTEMBARQUE#(lf)FROM SC9010 SC9#(lf)INNER JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SC9.C9_PRODUTO#(lf)INNER JOIN SC6010 SC6 ON SC6.D_E_L_E_T_ = '' AND SC6.C6_FILIAL = SC9.C9_FILIAL AND SC6.C6_NUM = SC9.C9_PEDIDO AND SC6.C6_ITEM = SC9.C9_ITEM#(lf)INNER JOIN SC5010 SC5 ON SC5.D_E_L_E_T_ = '' AND SC5.C5_FILIAL = SC9.C9_FILIAL AND SC5.C5_NUM = SC9.C9_PEDIDO#(lf)INNER JOIN SE4010 SE4 ON SE4.D_E_L_E_T_ = '' AND SE4.E4_CODIGO = SC5.C5_CONDPAG #(lf)INNER JOIN SF4010 SF4 ON SF4.D_E_L_E_T_ = '' AND SF4.F4_FILIAL = SC6.C6_FILIAL AND SF4.F4_CODIGO = SC6.C6_TES#(lf)LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SC5.C5_VEND1#(lf)LEFT JOIN SA3010 SA33 ON SA33.D_E_L_E_T_ = '' AND SA33.A3_COD = SC5.C5_VEND3#(lf)LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SC9.C9_CLIENTE AND SA1.A1_LOJA = SC9.C9_LOJA#(lf)LEFT JOIN DAK010 DAK ON DAK.D_E_L_E_T_ = '' AND DAK.DAK_COD = SC9.C9_CARGA AND (DAK.DAK_DATA IS NOT NULL OR DAK.DAK_FILIAL = SC9.C9_FILIAL)#(lf)LEFT JOIN SF2010 SF2 ON SF2.D_E_L_E_T_ = '' AND SF2.F2_FILIAL = SC9.C9_FILIAL AND SF2.F2_DOC = SC9.C9_NFISCAL AND SF2.F2_SERIE = SC9.C9_SERIENF#(lf)LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SC9.C9_CLIENTE AND SA2.A2_LOJA = SC9.C9_LOJA#(lf)WHERE SC9.D_E_L_E_T_ <> '*' #(lf)    AND SC9.C9_PRODUTO LIKE '%PA%'#(lf)GROUP BY #(lf)    SC9.C9_FILIAL,#(lf)    SC9.C9_PEDIDO,#(lf)    SC9.C9_CLIENTE,#(lf)    SC9.C9_LOJA,#(lf)    SC9.C9_PRODUTO,#(lf)    SC9.C9_ITEM,#(lf)    SC9.C9_SEQUEN;"]),
    #"Tipo de coluna alterado" = Table.TransformColumnTypes(Origem, {{"EMISSAONF", type date}, {"DTEMBARQUE", type date}, {"EMISSAOPED", type date}}),
  #"Colunas removidas" = Table.RemoveColumns(#"Tipo de coluna alterado", {"TES"})
in
  #"Colunas removidas";

shared DadosEntregaReal = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\EXPEDICAO\Controle de Embarques\Leidiane\PEDIDOSDEVENDACONSOLIDADO - ATT.xlsm"), null, true),
    DadosEntregaReal_Table = Fonte{[Item="DadosEntregaReal",Kind="Table"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(DadosEntregaReal_Table,{{"CHAVE", type text}, {"PEDIDO", Int64.Type}, {"TIPO OLD", type text}, {"TIPO NEW", type text}})
in
    #"Tipo Alterado";

shared dAgrupPROD = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\PUBLICA\T.I\01. BASES\fManual.xlsx"), null, true),
    dAgrupPROD_Table = Fonte{[Item="dAgrupPROD",Kind="Table"]}[Data],
    #"Tipo Alterado" = Table.TransformColumnTypes(dAgrupPROD_Table,{{"PRODUTO", type text}, {"GRUPO", type text}, {"SUBGRUPO", type text}})
in
    #"Tipo Alterado";

shared dRegiao = let
    Fonte = Excel.Workbook(File.Contents("\\192.168.67.201\Departamentos$\PUBLICA\T.I\01. BASES\fManual.xlsx"), null, true),
    dRegiao_Table = Fonte{[Item="dRegiao",Kind="Table"]}[Data],
    #"Texto Limpo" = Table.TransformColumns(dRegiao_Table,{{"Coluna 1", Text.Clean, type text}, {"Coluna 2", Text.Clean, type text}, {"Coluna 3", Text.Clean, type text}})
in
    #"Texto Limpo";

shared __STATUS__ = let
    Fonte = if Table.RowCount(Table.Combine({dAgrupPROD, dRegiao, DadosEntregaReal, PEDIDOSEMBARQUE})) > 0 then DateTime.LocalNow() else "Pendente"
in
    Fonte;

shared __SQL__ = let
    #"Linhas Filtradas" = Table.SelectRows(Record.ToTable(#shared), each Text.StartsWith([Name], "sql"))
in
    #"Linhas Filtradas";